spring.application.name=user-management

spring.datasource.url=jdbc:postgresql://db:5432/user-management
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=*

server.address=0.0.0.0
server.port=8080